#!/usr/bin/env bash
# Write the ClusterImageCatalog manifests for the published images, one per
# flavor and distro: catalogs/catalog-<flavor>-<distro>.yaml.
#
# Each entry points at the newest build of the pinned server version by its
# immutable tag and digest, read back from the registry, so applying a catalog
# is exactly as reproducible as pulling by digest.
#
# Usage:
#   IMAGE_PREFIX=ghcr.io/cnmsql images/catalog.sh [out-dir]
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=images/common.sh
. "${here}/common.sh"

: "${IMAGE_PREFIX:?IMAGE_PREFIX must be set}"
out="${1:-${repo_root}/catalogs}"
mkdir -p "${out}"
work="$(mktemp -d)"
trap 'rm -rf "${work}"' EXIT

for t in $(bake_targets); do
  json="$(target_json "$t")"
  current="$(jq -r '.tags[1]' <<<"$json")"
  labels="$(published_labels "${current}")"
  if [ -z "${labels}" ]; then
    echo "skip ${t}: ${current} is not published" >&2
    continue
  fi
  digest="$(published_digest "${current}")"
  flavor="$(jq -r '.["co.cnmsql.image.flavor"]' <<<"$labels")"
  distro="$(jq -r '.["co.cnmsql.image.distro"]' <<<"$labels")"
  series="$(jq -r '.["co.cnmsql.image.catalog-series"]' <<<"$labels")"
  server="$(jq -r '.["co.cnmsql.image.server-version"]' <<<"$labels")"
  build="$(jq -r '.["co.cnmsql.image.build"]' <<<"$labels")"
  printf '    - series: "%s"\n      image: %s:%s-%s-%s@%s\n' \
    "${series}" "${current%:*}" "${server}" "${build}" "${distro}" "${digest}" \
    >>"${work}/${flavor}-${distro}"
done

for f in "${work}"/*; do
  [ -e "$f" ] || { echo "nothing published" >&2; exit 1; }
  key="$(basename "$f")"
  flavor="${key%%-*}"
  {
    echo "# Generated by images/catalog.sh from the published images. Do not edit."
    echo "apiVersion: mysql.cnmsql.co/v1alpha1"
    echo "kind: ClusterImageCatalog"
    echo "metadata:"
    echo "  name: cnmsql-${key}"
    echo "spec:"
    echo "  flavor: ${flavor}"
    echo "  images:"
    cat "$f"
  } >"${out}/catalog-${key}.yaml"
  echo "wrote ${out}/catalog-${key}.yaml" >&2
done
